[tox]
envlist = py310,py311,coverage-report

[testenv]
deps = 
    pytest~=7.4.0
    pytest-cov>=4.0.0
    pytest-mock>=3.10.0
    coverage>=7.0.0
commands = pytest {posargs}

[testenv:coverage-report]
skip_install = True
deps =
    coverage>=7.0.0
commands =
    coverage combine
    coverage report --fail-under=85
    coverage html

[testenv:lint]
deps =
    pylint
    flake8
    black
commands =
    black src/
    flake8 src/
    pylint src/

[coverage:run]
branch = True
source = src

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
    if __name__ == .__main__.:
    if TYPE_CHECKING:
precision = 2
